


create table if not exists produtos (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null default auth.uid() references auth.users(id) on delete cascade,
  sku          text,
  nome         text,
  team         text not null,
  liga         text,
  temporada    text,
  marca        text,
  modelo       text,
  categoria    text,
  custo        numeric not null default 0,
  preco        numeric not null default 0,
  foto_url     text,
  observacoes  text,
  criado_em    timestamptz not null default now()
);


create table if not exists tamanhos_estoque (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  produto_id  bigint not null references produtos(id) on delete cascade,
  tamanho     text not null check (tamanho in ('PP','P','M','G','XL','2XL','3XL','4XL')),
  qtd         numeric not null default 0,
  unique (produto_id, tamanho)
);


create table if not exists movimentacoes (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null default auth.uid() references auth.users(id) on delete cascade,
  produto_id     bigint not null references produtos(id) on delete cascade,
  tamanho        text not null,
  tipo           text not null check (tipo in ('Entrada','Saída','Venda','Ajuste')),
  quantidade     numeric not null,
  valor_unitario numeric,
  motivo         text,
  observacao     text,
  data           timestamptz not null default now()
);


create table if not exists configuracoes (
  user_id       uuid primary key references auth.users(id) on delete cascade,
  company_name  text default 'Kadu Camisas de Time',
  logo_url      text,
  accent_color  text default '#e11d2e',
  telefone      text,
  endereco      text,
  instagram     text
);


alter table produtos enable row level security;
alter table tamanhos_estoque enable row level security;
alter table movimentacoes enable row level security;
alter table configuracoes enable row level security;

create policy "produtos_select_own" on produtos for select using (auth.uid() = user_id);
create policy "produtos_insert_own" on produtos for insert with check (auth.uid() = user_id);
create policy "produtos_update_own" on produtos for update using (auth.uid() = user_id);
create policy "produtos_delete_own" on produtos for delete using (auth.uid() = user_id);

create policy "tamanhos_select_own" on tamanhos_estoque for select using (auth.uid() = user_id);
create policy "tamanhos_insert_own" on tamanhos_estoque for insert with check (auth.uid() = user_id);
create policy "tamanhos_update_own" on tamanhos_estoque for update using (auth.uid() = user_id);
create policy "tamanhos_delete_own" on tamanhos_estoque for delete using (auth.uid() = user_id);

create policy "movimentacoes_select_own" on movimentacoes for select using (auth.uid() = user_id);
create policy "movimentacoes_insert_own" on movimentacoes for insert with check (auth.uid() = user_id);
create policy "movimentacoes_delete_own" on movimentacoes for delete using (auth.uid() = user_id);

create policy "configuracoes_select_own" on configuracoes for select using (auth.uid() = user_id);
create policy "configuracoes_insert_own" on configuracoes for insert with check (auth.uid() = user_id);
create policy "configuracoes_update_own" on configuracoes for update using (auth.uid() = user_id);


create or replace function registrar_movimentacao(
  p_produto_id bigint,
  p_tamanho text,
  p_tipo text,
  p_quantidade numeric,
  p_motivo text default '',
  p_observacao text default ''
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_produto produtos%rowtype;
  v_linha tamanhos_estoque%rowtype;
  v_delta numeric;
  v_qtd_atual numeric;
  v_nova_qtd numeric;
  v_valor_unitario numeric;
begin
  select * into v_produto from produtos where id = p_produto_id and user_id = auth.uid();
  if not found then
    return jsonb_build_object('ok', false, 'erro', 'Produto não encontrado.');
  end if;

  if p_tipo = 'Entrada' then
    v_delta := abs(p_quantidade);
  elsif p_tipo in ('Saída', 'Venda') then
    v_delta := -abs(p_quantidade);
  elsif p_tipo = 'Ajuste' then
    v_delta := p_quantidade;
  else
    return jsonb_build_object('ok', false, 'erro', 'Tipo de movimentação inválido.');
  end if;

  select * into v_linha from tamanhos_estoque
    where produto_id = p_produto_id and tamanho = p_tamanho and user_id = auth.uid();

  v_qtd_atual := coalesce(v_linha.qtd, 0);
  v_nova_qtd := v_qtd_atual + v_delta;

  if v_nova_qtd < 0 then
    return jsonb_build_object('ok', false, 'erro',
      'Estoque insuficiente no tamanho ' || p_tamanho || '. Disponível: ' || v_qtd_atual || ' unidade(s).');
  end if;

  if v_linha.id is null then
    insert into tamanhos_estoque (user_id, produto_id, tamanho, qtd)
    values (auth.uid(), p_produto_id, p_tamanho, v_nova_qtd);
  else
    update tamanhos_estoque set qtd = v_nova_qtd where id = v_linha.id;
  end if;

  v_valor_unitario := case when p_tipo = 'Venda' then v_produto.preco else null end;

  insert into movimentacoes (user_id, produto_id, tamanho, tipo, quantidade, motivo, observacao, valor_unitario)
  values (auth.uid(), p_produto_id, p_tamanho, p_tipo, abs(p_quantidade), nullif(p_motivo,''), nullif(p_observacao,''), v_valor_unitario);

  return jsonb_build_object('ok', true, 'novaQtd', v_nova_qtd);
end;
$$;


create policy "fotos_leitura_publica"
  on storage.objects for select
  using (bucket_id = 'fotos');

create policy "fotos_upload_dono"
  on storage.objects for insert
  with check (bucket_id = 'fotos' and auth.uid()::text = (storage.foldername(name))[1]);

create policy "fotos_delete_dono"
  on storage.objects for delete
  using (bucket_id = 'fotos' and auth.uid()::text = (storage.foldername(name))[1]);
